version: '2'
services:
  postgresratmap: #how to add custom conf
    image: postgres
    env_file: .env    
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./config/postgresql.conf:/etc/postgresql.conf
      - ./log/postgresql/:/log/
    ports:
      - '127.0.0.1:5432:5432'
  postgresratmap_backup: 
    #image: martianrock/pg_backup_rotated
    build: db_backup_script 
    env_file: .env    
    volumes:
        - ./backup:/backups/
    links:
        - postgresratmap

  redis:
    image: redis
    command: redis-server
    ports:
      - '127.0.0.1:6379:6379'

  ratmap:
    build: .
    env_file: .env
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf    
    volumes:
      - .:/ratmap
      - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf  
    ports:
        - '127.0.0.1:30001:30001'
        - '127.0.0.1:30000:30000'
    links:
      - postgresratmap 
      - redis

#TODO:
#* change volume mount in production
# - mount ro everything mount rw sharred
#* database backup
#* watchtower
