default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  
development:
  <<: *default
  database: ratmap_development

test:
  <<: *default
  database: ratmap_test

production:
  <<: *default
  database: ratmap_production
  host:     <%= ENV['POSTGRES_CONTAINER'] %> 
  username: <%= ENV['POSTGRES_USER'] %> 
  password: <%= ENV['POSTGRES_PASSWORD'] %> 

